Lesson 14 work with external API
mubat/testguru_rails_course pull request #14
Opened 2021-07-20 11:12 UTC by mubat

2021-07-20 17:16 UTC, BubuntuClu requested changes

2021-07-20 17:16 UTC, BubuntuClu commented on app/services/gist_question_service.rb
> +    save_gist response, @question
параметры в скобках указывай

2021-07-20 17:16 UTC, BubuntuClu commented on app/services/gist_question_service.rb
> +    save_gist response, @question
не уверен что это правильное место для этого метода.  этот сервис общается с гитом, не думаю что стоит сюда вплетать создание записей в БД

2021-07-20 17:16 UTC, BubuntuClu commented on app/views/admin/gists/_gist.html.erb
> +  <td><%= gist.question.body[0..25] %></td>
есть метод truncate, который за тебя обрежет все как надо

2021-07-20 17:16 UTC, BubuntuClu commented on app/helpers/application_helper.rb
> +    case level
давай луше хэш сделаем вместо кейса

2021-07-20 17:16 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +    if result.key?(:html_url)
сделай в сервисе метод `success?`, который на основе метода `last_response` из октокита будет узнавать как прошел процесс создания гиста в гите.

2021-07-20 17:53 UTC, mubat commented on app/services/gist_question_service.rb
> +    save_gist response, @question
Я тоже так думал, что там ему не место. Но в таком случае нужно это делать в контроллере. Но тогда контроллер не будет тонким. Куда стоит вынести?

2021-07-21 06:15 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +      Gist.create(question: @test_passage.current_question, url: gist_service.url, user: current_user)
`current_user.gists.create...`

2021-07-21 08:43 UTC, merged