Lesson 18.1 add Badge
mubat/testguru_rails_course pull request #18
Opened 2021-07-24 23:00 UTC by mubat

2021-07-25 15:36 UTC, BubuntuClu requested changes

2021-07-25 15:36 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +  include BadgeHelper
для чего в контроллер требуется подклчюать методы из хэлперов вьюх?

2021-07-25 15:36 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +      register_flashes BadgesService.new(@test_passage).find.reward.badges
так не пишут. нужно наверное какое-то условие добавить или еще что-то.
ааааа, это параметры. надо скобки ставить, очень плохой стиль написания кода без скобок

2021-07-25 15:36 UTC, BubuntuClu commented on app/services/badges_service.rb
> +  RULES = [
при создании бейджа назначай какое нибудь правило из этого списка

2021-07-25 15:36 UTC, BubuntuClu commented on app/services/badges_service.rb
> +    RULES.each_with_index do |rule, index|
когда ты правило назначишь в бейдже тебе проще будет сделать перебор по `Badge.all` и не надо будет костылять `Badge.where(rule: index).to_a` и прочее. у тебя уже будет бейдж который можно доабвить в мользователя

так же саму проверку стоит вынести в этот сервис. модель правил не должна знать о проверках, она просто хранит в себе денные

2021-07-25 15:36 UTC, BubuntuClu commented on app/services/badges_service.rb
> +    RULES.each_with_index do |rule, index|
```
Badge.all.each do |badge|
 user.badges << badge if senf("#{badge.rule}_award?, badge.value)
end
```
перебираем баджи, вызываем метод на оснвое имени правила и передаем параметр для метода

2021-07-25 15:36 UTC, BubuntuClu commented on app/services/rules/rule_category.rb
> +    all_test_passages.each { |test_passage| return false unless test_passage.passed? }
эту проверку надо делать на уровне БД, можно добавить столбец с отметкой о том успешно пройден тест или нет

2021-07-25 15:36 UTC, BubuntuClu commented on app/services/rules/rule_first_attempt.rb
> +class Rules::RuleFirstAttempt < Rules::RuleBase
о, прикольно, можно и так да. можно тогда из send вызывать метод проверки правила

2021-07-25 15:36 UTC, BubuntuClu commented on app/services/rules/rule_first_attempt.rb
> +    @test_passage.user.tests.where(id: @test_passage.test.id).count == 1 && @test_passage.passed?
`&& @test_passage.passed?` мне кажется, это иззлишняя проверка. можно вообще сервис не вызывать, когда тест пройден неуспешно. можно вынести на уровень выше, в контроллер

2021-07-25 15:50 UTC, mubat commented on app/services/rules/rule_first_attempt.rb
> +    @test_passage.user.tests.where(id: @test_passage.test.id).count == 1 && @test_passage.passed?
Там правило: "Выдать бэйдж после успешного прохождения теста с первой попытки". Т.е. нужно проверить:

1. тест пройден успешно
2. других прохождений этого теста у юзера нет. 

Не вижу смысла выносить. Может условие у меня неправильно описано?

2021-07-25 15:55 UTC, mubat commented on app/services/rules/rule_category.rb
> +    all_test_passages.each { |test_passage| return false unless test_passage.passed? }
В приложении хранится количество ответов, а валидация для процента прохождения - как по мне, это изначально была неправильная архитектура приложения в этом месте. Из-за этого я мурыжил эту ерунду пару часов, чтобы составить SQL запрос, который считал бы это - так и не получилось. Поэтому сделал таким способом. 
Предлагаю добавить колонку, в которой хранить % прохождения. Такой вариант приемлем?

2021-07-25 15:56 UTC, mubat commented on app/services/badges_service.rb
> +  RULES = [
не понял. При создании бэйджа указывается правило. И поле обязательно. Что не так?

2021-07-25 15:59 UTC, mubat commented on app/controllers/test_passages_controller.rb
> +      register_flashes BadgesService.new(@test_passage).find.reward.badges
Это методы, не параметры. 
Если переписать без такого вида, получится так:
```ruby
service = BadgesService.new(@test_passage)
service.reward # поиск будет уже встроен в этот метод
register_flashes service.badges
```
Получается, вместо одной строки будет 3. Но я не стал этот вариант использовать, потому что в Rails борются за количество строк. 
Как поступить?

2021-07-25 16:08 UTC, mubat commented on app/controllers/test_passages_controller.rb
> +  include BadgeHelper
Это я пытался картинку в alert вывести. Не получилось. Здесь забыл убрать. Уберу

2021-07-25 16:17 UTC, mubat commented on app/services/badges_service.rb
> +    RULES.each_with_index do |rule, index|
В таком случае каждое правило будет выполнятся отдельно. А при текущей структуре можно повесить одно правило на несколько бэйджев. И для каждого будет запускаться правило.
Стоит ли на это не обращать внимание и сделать как ты показал?

2021-07-25 16:40 UTC, mubat commented on app/services/badges_service.rb
> +    list = []
Есть ли какой-то вариант написания кода, чтобы не создавать временную переменную для сохранения результата?

2021-07-25 16:59 UTC, BubuntuClu commented on app/services/badges_service.rb
> +    RULES.each_with_index do |rule, index|
поправил метод

2021-07-25 17:03 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +      register_flashes BadgesService.new(@test_passage).find.reward.badges
нет войны за количество строк, есть война за читаемость. каждая операция с новой строки.
`register_flashes(BadgesService.new(@test_passage).call)` -  как вариант, но лучше разделить на разные строки

`register_flashes BadgesService.new(@test_passage).find.reward.badges`
`register_flashes(badges)`
вот что я имел в виду под параметрами. ты сам видать запутался и не понял о чем речь. ставь всегда скобки когда передаешь параметры, я тебе часто это пишу, вот как пример - https://github.com/mubat/testguru_rails_course/pull/14#discussion_r673320180

2021-07-25 17:04 UTC, BubuntuClu commented on app/services/badges_service.rb
> +    RULES.each_with_index do |rule, index|
поправил метод выше

2021-07-25 17:11 UTC, BubuntuClu commented on app/services/badges_service.rb
> +    list = []
перебор через `map`если это массив или `with_object(arg)`  - где вместо arg указываешь объект который использовать

2021-07-25 17:11 UTC, BubuntuClu commented on app/services/badges_service.rb
> +    RULES.each_with_index do |rule, index|
ну у тебя все равно для каждого бейджа свое правило и аргумент(если его добавить). зачем тебе бейджи с одинаковыми правилами? я не вижу в этом смысла. плюс бейдж ты можешь скрыть и не выдавать конректыный бейдж, а с твоими правилами как потом поступать? ты задал в несколько беджей правило и как сделать так чтобы оно не работало на какой-то 1 бейдж?

2021-07-25 17:11 UTC, BubuntuClu commented on app/services/rules/rule_category.rb
> +    all_test_passages.each { |test_passage| return false unless test_passage.passed? }
у тебя есть метод, который говорит успешено ли пройден тест, вот когда ты его вызываешь, при успехе ты можешь в новом поле пассажа записать что он успешно пройден. и это даст тебе возможность получить все успешные тесты одной строкой в `where`, а сейчас ты получишь все пассажи из БД, а потом еще рубями их фильтруешь через логику написанную на рубях. это просто не оптимально

2021-07-25 17:11 UTC, BubuntuClu commented on app/services/rules/rule_first_attempt.rb
> +    @test_passage.user.tests.where(id: @test_passage.test.id).count == 1 && @test_passage.passed?
ну смотить, если тест пройден не успешно, есть смысл вызывать сервис с наградой? мне кажется, нет. вот и получается что это условие тут не нужно будет по логическим соображениям

2021-07-25 18:33 UTC, mubat commented on app/services/rules/rule_first_attempt.rb
> +    @test_passage.user.tests.where(id: @test_passage.test.id).count == 1 && @test_passage.passed?
Если сейчас перенести, а потом понадобится добавить правило, которое не будет включать "удачные" прохождения? Это явно относится к проверке правила.  И тут точно нельзя переносить в другое место.
Единственное, что стоит сделать - поменять местами проверки, чтобы не выполнялись запросы в БД, как ты сказал, когда пройден не успешно (что есть в условии правила).

2021-07-25 18:40 UTC, mubat commented
- Убрал подключение хелперов (детально - в комментарии)
- разбил вызов сервиса по награждению на отдельные команды
- чуть поменял сохранение Правил в Бэйдж (теперь имя класса хранится)
- Укоротил цикл по награждению
- добавил поле "процент успешных ответов". Заполняется только после окончания тестирования
- Переделал формирование SQL запросов на использование этого нового поля. Теперь только 1 запрос проверяет.
- поменял местами проверку "успешно пройден" и количества пройденных в Правиле "С первой попытки" (детально - в комментарии)
- Add Comment...
-

2021-07-26 07:26 UTC, BubuntuClu commented on app/models/test_passage.rb
> +  before_update :bef_update_set_passed_percent # set only if test completed
bef_update_set_passed_percent - в имя метода не стоит включать имя колбэка. у тебя и так сначала идет тип колбэка, а потом функция для него

2021-07-26 07:26 UTC, BubuntuClu commented on app/services/rules/rule_category.rb
> +    !test_passage.user.test_passages.where(test_id: Test.where(category: test_passage.test.category))
а этот метод тебе что возвращает? есть ли удачные прохождения тестов. из этой категории? это не то что нужно. нужно проверить что все тесты из категории пройдены. точно так же и с уровнем

2021-07-26 07:41 UTC, mubat commented on app/models/test_passage.rb
> +  before_update :bef_update_set_passed_percent # set only if test completed
https://thinknetica.teachbase.ru/viewer/sessions/117346/materials/192834
Урок 9. Лекция "Обратные вызовы (callbacks) в моделях". 9:40 - а тут говорится, что так лучше делать. 
Мне также не нравится ставить этот лишний префикс. Но вопрос в другом - как принято делать?

2021-07-26 07:45 UTC, merged