Lesson 4 ActiveRecord query interface
mubat/testguru_rails_course pull request #4
Opened 2021-06-14 16:03 UTC by mubat

2021-06-14 18:23 UTC, BubuntuClu requested changes

2021-06-14 18:23 UTC, BubuntuClu commented on app/models/test.rb
> +    joins(:category).where(category: { title: category_name}).pluck(:title)
сортировку по убыванию еще добавить надо

2021-06-14 18:23 UTC, BubuntuClu commented on db/seeds.rb
> +                      { title: 'Я слишком молод, чтобы умереть', level: 0, category_id: 3 },
нельзя хардкордить ID. используй объекты. создал категории - поместил в массив. используешь этот массив при создании тестов. и тд

2021-06-15 07:12 UTC, BubuntuClu commented on db/seeds.rb
> +                ])
ответы для вопросов заполнить бы еще

2021-06-19 10:02 UTC, merged

2021-06-19 18:23 UTC, mubat commented on db/seeds.rb
> +                ])
Добавил в следующем ПР https://github.com/mubat/testguru_rails_course/pull/5/commits/6daa4a20beb603a6521c95537a42865539cc59cb