Lesson 6 validation and scope methods
mubat/testguru_rails_course pull request #6
Opened 2021-06-23 16:33 UTC by mubat

2021-06-24 05:59 UTC, BubuntuClu requested changes

2021-06-24 05:59 UTC, BubuntuClu commented on app/models/question.rb
> +  validates :answers, length: { minimum: 1, maximum: 4 }
при создании ответа, у тебя не валидируется вопрос. эта валидации должна быть в другой моделе. и валидация должна быть кастомной, стандартными способами не провалидировать нужное поведение

2021-06-24 05:59 UTC, BubuntuClu commented on app/models/test.rb
> +    joins(:category).where(category: { title: category_name }).order(id: :desc).pluck(:title)
сортировку и выборку не надо помещать в скоуп.
скоуп должен возвращать объект ActiveRecord::Relation, pluck возвращает массив.
так же скоуп это универсальный метод, который может использован в разных частях приложения, там может потребоваться другая сортировка и выборка.
метод надо оставить, заменить часть выражения на скоуп и уже к скоупу применить сортировку и выборку

2021-06-24 05:59 UTC, BubuntuClu commented on app/models/test.rb
> +  validates :title, :level, presence: true
`validates :title, :level, presence: true, uniqueness: { scope: :level }`

2021-06-24 05:59 UTC, BubuntuClu commented on app/models/test.rb
> +  validates :title, uniqueness: { scope: :level }
ограничения надо дублировать на всех уровнях приложения. можно через СУБД насоздавать данных, которые для приложения не будут валидны. в БД добавить уникальный составной индекс надо

2021-06-24 13:35 UTC, mubat commented on app/models/test.rb
> +    joins(:category).where(category: { title: category_name }).order(id: :desc).pluck(:title)
Вынес `order().pluck()` в отдельный метод. Там же вызывается scope метод

2021-06-24 13:36 UTC, mubat commented on app/models/test.rb
> +  validates :title, :level, presence: true
Сделал, но не понял, по какой схеме Rails помимает, как применить правило `uniqueness`

2021-06-24 13:39 UTC, mubat commented on app/models/test.rb
> +  validates :title, uniqueness: { scope: :level }
добавил ключ уникальности в БД

2021-06-24 14:45 UTC, mubat commented on app/models/test.rb
> +  validates :title, :level, presence: true
Попробовал создать с таким правилом тест с отличием только в названии - мне выдало ошибку. Поэтому вернул обратно раздельное объявление правил

2021-06-24 18:47 UTC, BubuntuClu commented on app/models/test.rb
> +  validates :title, :level, presence: true
что за ошибка? давай сразу всю инфу по событиям, чтобы не было лишних итераций.

работает это так же как и в БД, только на уровне моделей. то есть на связку полей. дополнительной уникальности только на level это не накладывает

2021-06-24 18:50 UTC, BubuntuClu requested changes

2021-06-24 18:50 UTC, BubuntuClu commented on app/models/answer.rb
> +    errors.add(:question, 'should has answers') unless question.answers.exists?
а как первый ответ тогда создать? у тебя же вопрос без ответов создается

2021-06-24 18:50 UTC, BubuntuClu commented on app/models/answer.rb
> +  validate :validate_answers_count, if: -> { question.present? }
у тебя не может ббыть ответ без вопроса, он тогда не будет создан.

тут можно заменить на `on: :create`

2021-06-24 18:50 UTC, BubuntuClu commented on app/models/answer.rb
> +  attribute :is_correct, default: false
это тут зачем? ты в миграции задал уже все

2021-06-24 18:50 UTC, BubuntuClu commented on app/models/question.rb
> +  validates :answers, length: { minimum: 1, maximum: 4 }
это надо удалить

2021-06-24 18:50 UTC, BubuntuClu commented on app/models/user.rb
> +  scope :find_tests_by_level, ->(level) { tests.where(level: level) }
этот не равноценая замена метода. надо вернуть метод, скоуп не работает так же как и метод

2021-06-24 18:50 UTC, BubuntuClu commented on db/migrate/20210624111520_add_unique_for_title_in_tests.rb
> +  def up
```
 def change
    add_index(:tests, [:title, :level], unique: true)
  end
```

2021-06-24 19:06 UTC, mubat commented on app/models/test.rb
> +  validates :title, :level, presence: true
<ins>В случае, если указать `uniqueness` для обоих полей:</ins>

1. Проверка, что есть в базе
```ruby
2.7.0 :063 > Test.pluck(:title, :level)
   (0.4ms)  SELECT "tests"."title", "tests"."level" FROM "tests"
 => [["Я слишком молод, чтобы умереть", 0], ["Эй, не так грубо", 1], ["Сделай мне больно", 2], ["Сверхнасилие", 3], ["Кошмар!", 4], ["Кошмар!2", 4]] 
```
2. Создаю объект с уже существующими значениями:
```ruby
2.7.0 :065 > new_test = Test.new(title: "Кошмар!2", level: 4, created_by_id: 1, category_id: 1)
2.7.0 :066 > new_test.valid?
  Category Load (0.3ms)  SELECT "categories".* FROM "categories" WHERE "categories"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  User Load (0.2ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  Test Exists? (0.3ms)  SELECT 1 AS one FROM "tests" WHERE "tests"."title" = $1 AND "tests"."level" = $2 LIMIT $3  [["title", "Кошмар!2"], ["level", 4], ["LIMIT", 1]]
  Test Exists? (0.2ms)  SELECT 1 AS one FROM "tests" WHERE "tests"."level" = $1 AND "tests"."level" = $2 LIMIT $3  [["level", 4], ["level", 4], ["LIMIT", 1]]
 => false 
2.7.0 :067 > new_test.errors
 => #<ActiveModel::Errors:0x0000559cd54e40e0 @base=#<Test id: nil, title: "Кошмар!2", level: 4, category_id: 1, created_at: nil, updated_at: nil, created_by_id: 1>, @errors=[#<ActiveModel::Error attribute=title, type=taken, options={:value=>"Кошмар!2"}>, #<ActiveModel::Error attribute=level, type=taken, options={:value=>4}>]> 
```
3. Указываю новое значение для `title`, чтобы пара стала уникальной:
```ruby
2.7.0 :068 > new_test.title = "Кошмар!3"
2.7.0 :069 > new_test.valid?
  Test Exists? (0.4ms)  SELECT 1 AS one FROM "tests" WHERE "tests"."title" = $1 AND "tests"."level" = $2 LIMIT $3  [["title", "Кошмар!3"], ["level", 4], ["LIMIT", 1]]
  Test Exists? (0.3ms)  SELECT 1 AS one FROM "tests" WHERE "tests"."level" = $1 AND "tests"."level" = $2 LIMIT $3  [["level", 4], ["level", 4], ["LIMIT", 1]]
 => false 
2.7.0 :070 > new_test.errors
 => #<ActiveModel::Errors:0x0000559cd54e40e0 @base=#<Test id: nil, title: "Кошмар!3", level: 4, category_id: 1, created_at: nil, updated_at: nil, created_by_id: 1>, @errors=[#<ActiveModel::Error attribute=level, type=taken, options={:value=>4}>]> 
```
3. Указываю новое значение для `level` (`title` остаётся прежним), чтобы пара стала уникальной:
```ruby
2.7.0 :094 > new_test.title
 => "Кошмар!2" 
2.7.0 :095 > new_test.level = 3
2.7.0 :096 > new_test.valid?
  Test Exists? (0.4ms)  SELECT 1 AS one FROM "tests" WHERE "tests"."title" = $1 AND "tests"."level" = $2 LIMIT $3  [["title", "Кошмар!2"], ["level", 3], ["LIMIT", 1]]
  Test Exists? (0.3ms)  SELECT 1 AS one FROM "tests" WHERE "tests"."level" = $1 AND "tests"."level" = $2 LIMIT $3  [["level", 3], ["level", 3], ["LIMIT", 1]]
 => false 
2.7.0 :097 > new_test.errors
 => #<ActiveModel::Errors:0x0000559cd5a10938 @base=#<Test id: nil, title: "Кошмар!2", level: 3, category_id: 1, created_at: nil, updated_at: nil, created_by_id: 1>, @errors=[#<ActiveModel::Error attribute=level, type=taken, options={:value=>3}>]> 
```
В этом месте валидация должна проходить, но мне ругается на уникальность поля `level`. И валидация проходит только когда я указываю `level` которого вообще нет в базе (например, 6)



<ins>В случае, если указать `uniqueness` для обоих полей:</ins>
1. Перезагружаю консоль.
2. Проверка, что есть в базе
```ruby
2.7.0 :077 > Test.pluck(:title, :level)
   (0.1ms)  SELECT "tests"."title", "tests"."level" FROM "tests"
 => [["Я слишком молод, чтобы умереть", 0], ["Эй, не так грубо", 1], ["Сделай мне больно", 2], ["Сверхнасилие", 3], ["Кошмар!", 4], ["Кошмар!2", 4]] 
```
3. Создаю объект с уже существующими значениями:
```ruby
2.7.0 :081 > new_test = Test.new(title: "Кошмар!2", level: 4, created_by_id: 1, category_id: 1)
2.7.0 :082 > new_test.valid?
  Category Load (0.2ms)  SELECT "categories".* FROM "categories" WHERE "categories"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  User Load (0.2ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  Test Exists? (0.2ms)  SELECT 1 AS one FROM "tests" WHERE "tests"."title" = $1 AND "tests"."level" = $2 LIMIT $3  [["title", "Кошмар!2"], ["level", 4], ["LIMIT", 1]]
 => false 
2.7.0 :083 > new_test.errors
 => #<ActiveModel::Errors:0x0000559cd69ac950 @base=#<Test id: nil, title: "Кошмар!2", level: 4, category_id: 1, created_at: nil, updated_at: nil, created_by_id: 1>, @errors=[#<ActiveModel::Error attribute=title, type=taken, options={:value=>"Кошмар!2"}>]> 
```
4. Указываю новое значение для `level`, чтобы пара стала уникальной:
```ruby
2.7.0 :084 > new_test.level = 3
2.7.0 :085 > new_test.valid?
  Test Exists? (0.4ms)  SELECT 1 AS one FROM "tests" WHERE "tests"."title" = $1 AND "tests"."level" = $2 LIMIT $3  [["title", "Кошмар!2"], ["level", 3], ["LIMIT", 1]]
 => true 
2.7.0 :086 > new_test.errors
 => #<ActiveModel::Errors:0x0000559cd69ac950 @base=#<Test id: nil, title: "Кошмар!2", level: 3, category_id: 1, created_at: nil, updated_at: nil, created_by_id: 1>, @errors=[]> 
```

2021-06-24 19:52 UTC, mubat commented on db/migrate/20210624111520_add_unique_for_title_in_tests.rb
> +  def up
Когда искал этот метод, как-то пропустил его из виду
Исправил

2021-06-24 19:53 UTC, mubat commented on app/models/user.rb
> +  scope :find_tests_by_level, ->(level) { tests.where(level: level) }
Посмотрел как работают оба вариант. Примерно понял что и как.
Вернул изначальный вид.

2021-06-24 19:53 UTC, mubat commented on app/models/question.rb
> +  validates :answers, length: { minimum: 1, maximum: 4 }
удалил

2021-06-24 19:53 UTC, mubat commented on app/models/answer.rb
> +  attribute :is_correct, default: false
Удалил. 
Но немного не понял, откуда берётся значение по-умолчанию? Rails ставит исходя из схемы БД?

2021-06-24 19:54 UTC, mubat commented on app/models/answer.rb
> +  validate :validate_answers_count, if: -> { question.present? }
заменил на `on: :create`

2021-06-24 19:54 UTC, mubat commented on app/models/answer.rb
> +    errors.add(:question, 'should has answers') unless question.answers.exists?
проверил создание первого Ответа - действительно, не создаётся.
Убрал проверку.

2021-06-25 07:33 UTC, BubuntuClu commented on app/models/answer.rb
> +  attribute :is_correct, default: false
типа того. модель это и есть твоя таблица, только в контексте приложения

2021-06-25 07:39 UTC, BubuntuClu commented on app/models/test.rb
> +  validates :title, :level, presence: true
у тебя в обоих случаях `В случае, если указать uniqueness для обоих полей:`
1 - в итоге в первом я так понимаю уникальность разная на каждое поле?
тогда у тебя будет каждый раз ошибка если будет встречаться такое значение у любой из записей
тут всегда оба поля должны быть уникальные

2 - ну вроде же все правильно? создал для тайтла другое значение уровня и оно уже как пара ни с чем не совпадает

2021-06-25 07:53 UTC, mubat commented on app/models/test.rb
> +  validates :title, :level, presence: true
Работает с отдельным правилом уникальности, потому что, как я понял, в случае правила `validates :title, :level, uniqueness: { scope: :level }` будет работать 2 правила: уникальность пары `:title - :level` и уникальность пары `:level - :level`, т. е. просто по одному полю `:level`. Поэтому и не сработал первый вариант, когда я поменял только `:level`. Причём на одно из значений, которое уже используется (1..5)

2021-06-26 14:53 UTC, merged