Lesson 8 rails views
mubat/testguru_rails_course pull request #8
Opened 2021-07-07 17:21 UTC by mubat

2021-07-07 18:42 UTC, BubuntuClu requested changes

2021-07-07 18:42 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @question.update(question_params)
эту строку надо поместить в `if`

2021-07-07 18:42 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    if @question.save
будет так
`if @question.update(question_params)`

сейчас ты сначала обновляешь, уходит запрос в БД на обновление, потом сохраняешь и тоже уходит запрос в БД на обновление

2021-07-07 18:42 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +      render action: :edit
`render :edit`

2021-07-07 18:42 UTC, BubuntuClu commented on app/helpers/questions_helper.rb
> +    question.present? ? "Изменение данных в вопросе #{question.body}" : 'Добавление нового вопроса'
тут надо использовать `new_record?/persisted?` чтобы определить существует он или нет. а `present?` показывает просто передал ты объект или нет

2021-07-07 18:42 UTC, BubuntuClu commented on app/helpers/tests_helper.rb
> +    test.present? ? "Изменение теста #{@test.title}" : 'Добавление нового теста'
аналогично и тут

2021-07-07 18:42 UTC, BubuntuClu commented on config/routes.rb
> +  resources :categories, shallow: true do
на верхнем уровне нет смысла от `shallow: true`

2021-07-07 18:42 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    @category = Category.find(params[:category_id])
а где круд для категорий если ты это делаешь? ресурс в роуты добавил, а контроллеры и вьюхи не добавил. может лучше сделать селектор на странице создания теста, где ты выбираешь категорию, а не полный круд для категорий сделать?

2021-07-07 18:42 UTC, BubuntuClu commented on app/views/questions/edit.html.erb
> +<%= render 'form', model: @question, form_method: :patch %>
вообще без `form_method` метод должно работать. нужно передавать два объекта для определения метода и пути - @test и @question

2021-07-07 18:42 UTC, BubuntuClu commented on app/views/questions/index.html.erb
> +<%= render 'list', elements: @test.questions %>
вынеси сюда то, что у тебя в list, а тут сделай просто `render @test.questions`
в файле лист смысла большого нет

2021-07-07 18:42 UTC, BubuntuClu commented on app/views/tests/_form.html.erb
> +
сюда добавь еще выбор категории

2021-07-07 18:42 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    @test.questions.destroy_all
чтобы руками это не делать, есть опция `dependent` для ассоциаций, посмотри на нее

2021-07-07 18:42 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    params.require(:test).permit(:title, :level, :category_id)
ты на вьюхе выбираешь пользователя, а тут параметры его не передаешь

2021-07-07 18:43 UTC, BubuntuClu commented on app/helpers/application_helper.rb
> +    "https://github.com/#{author}/#{repo}"
возвращай сразу хэлпер `link_to`

2021-07-07 21:10 UTC, mubat commented on app/controllers/questions_controller.rb
> +    @question.update(question_params)
исправил

2021-07-07 21:10 UTC, mubat commented on app/controllers/questions_controller.rb
> +    if @question.save
исправил

2021-07-07 21:11 UTC, mubat commented on app/controllers/questions_controller.rb
> +      render action: :edit
поменял на string имя, убрал `action`

2021-07-07 21:11 UTC, mubat commented on app/helpers/questions_helper.rb
> +    question.present? ? "Изменение данных в вопросе #{question.body}" : 'Добавление нового вопроса'
исправил

2021-07-07 21:11 UTC, mubat commented on app/helpers/tests_helper.rb
> +    test.present? ? "Изменение теста #{@test.title}" : 'Добавление нового теста'
исправил

2021-07-07 21:13 UTC, mubat commented on config/routes.rb
> +  resources :categories, shallow: true do
убрал Категорию из роутов. 
_ Думал, что будет иерархия " Категория -> Тест -> Вопрос", поэтому сделал такое дерево. Хотя были сомнения насчёт этого решения_

2021-07-07 21:13 UTC, mubat commented on app/controllers/tests_controller.rb
> +    @category = Category.find(params[:category_id])
Переделал, чтобы Категория выбиралась на форме

2021-07-07 21:16 UTC, mubat commented on app/views/questions/edit.html.erb
> +<%= render 'form', model: @question, form_method: :patch %>
убрал. Настроил, чтобы указывать только модель

2021-07-07 21:17 UTC, mubat commented on app/views/questions/index.html.erb
> +<%= render 'list', elements: @test.questions %>
не изменял - на предыдущем уроке было задание, чтобы выводить этот список в 2х местах: на `index` странице Вопроса и на `view` странице Теста. Поэтому и был сделан паршиал

2021-07-07 21:19 UTC, mubat commented on app/views/tests/_form.html.erb
> +
добавил

2021-07-07 21:19 UTC, mubat commented on app/controllers/tests_controller.rb
> +    @test.questions.destroy_all
ещё на прошлом уроке нашёл этот конфиг. Пробовал его, вертел и так, и сяк - не получилось запустить его. Не удалялись подсущности.

2021-07-07 21:20 UTC, mubat commented on app/controllers/tests_controller.rb
> +    params.require(:test).permit(:title, :level, :category_id)
добавил недостающий параметр

2021-07-08 18:07 UTC, BubuntuClu approved these changes

2021-07-08 18:07 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    @test.questions.destroy_all
можно убрать, раз ты в ассоциации добавил зависимость на удаление

2021-07-08 18:07 UTC, BubuntuClu commented on app/models/question.rb
> +  has_many :answers, inverse_of: :question, dependent: :delete_all
`dependent: ::destroy` исопльзуй эту опцию, чтобы колбэки удаленных объектов тоже отрабатывали, если они есть

2021-07-08 18:07 UTC, BubuntuClu commented on app/models/test.rb
> +  has_many :questions, dependent: :delete_all
тут тоже про колбэки

2021-07-08 18:07 UTC, BubuntuClu commented on app/views/questions/show.html.erb
> +<%= link_to '<< к списку', test_path(@question.test), method: :get %>
а зачем тут метод указывать? тут и так гет будет

2021-07-10 10:04 UTC, mubat commented on app/views/questions/show.html.erb
> +<%= link_to '<< к списку', test_path(@question.test), method: :get %>
убрал

2021-07-10 10:04 UTC, mubat commented on app/models/test.rb
> +  has_many :questions, dependent: :delete_all
исправил

2021-07-10 10:04 UTC, mubat commented on app/models/question.rb
> +  has_many :answers, inverse_of: :question, dependent: :delete_all
исправил

2021-07-10 10:04 UTC, merged